-- Add missing columns to cases table
ALTER TABLE cases ADD COLUMN IF NOT EXISTS court_no VARCHAR(50);
ALTER TABLE cases ADD COLUMN IF NOT EXISTS file_year INTEGER;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS file_no INTEGER;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS file_type_id UUID REFERENCES lookup_values(id) ON DELETE SET NULL;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_cases_file_type ON cases(file_type_id);
